'use strict';

// tests for imgageAnalysis
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('imgageAnalysis', '/handler.js', 'main');

describe('imgageAnalysis', () => {
  before((done) => {
    done();
  });

  it('should return 400 (bad request) if imageUrl is not passed as parameter', () => {

    return wrapped.run({}).then(response => {
      console.log(response)
      expect(response).to.not.be.empty;
      expect(response.statusCode).to.equal(400);
    })

  });

  it('implement tests here', async () => {
    const response = await wrapped.run({ queryStringParameters: '{ "imageUrl": "hello" }' });
    expect(response).to.not.be.empty;
  });
});
